import { useEffect, useState } from 'react';
import { NavLink, Route, Routes, useParams } from 'react-router-dom';
import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardList, FileText, HeartPulse, Home, LayoutDashboard, LogOut, Menu, Shield, Smartphone, Users, WalletCards, X } from 'lucide-react';
import { Auth } from './Auth';
import { supabase } from './lib/supabase';
import { getOrCreateFamily, listMapItems, saveMapItem, type Family, type MapItem } from './lib/data';

const maps = [
 {id:'pessoas',label:'Pessoas',icon:Users,desc:'Quem faz o quê na família?'},{id:'saude',label:'Saúde',icon:HeartPulse,desc:'Informações essenciais de saúde.'},{id:'patrimonio',label:'Patrimônio',icon:Home,desc:'Bens, seguros e documentos.'},{id:'dinheiro',label:'Dinheiro',icon:WalletCards,desc:'Contas, compromissos e referências.'},{id:'casa',label:'Casa & Rotina',icon:ClipboardList,desc:'Contas e tarefas que não podem parar.'},{id:'digital',label:'Vida Digital',icon:Smartphone,desc:'Onde encontrar acessos, sem guardar senhas.'},{id:'emergencia',label:'Emergência',icon:AlertTriangle,desc:'O que fazer quando algo acontece.'},
];
function Layout({children,onLogout}:{children:React.ReactNode;onLogout:()=>void}){const[open,setOpen]=useState(false);return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">D</div><div><strong>Dossiê Familiar</strong><span>360™</span></div><button className="icon-btn mobile-only" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X size={22}/></button></div><nav><NavLink to="/" end onClick={()=>setOpen(false)}><LayoutDashboard size={19}/>Visão geral</NavLink>{maps.map(m=><NavLink key={m.id} to={'/mapa/'+m.id} onClick={()=>setOpen(false)}><m.icon size={19}/>{m.label}</NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/seguranca"><Shield size={19}/>Segurança e privacidade</NavLink><button className="logout" onClick={onLogout}><LogOut size={19}/>Sair</button></div></aside><main className="main"><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setOpen(true)} aria-label="Abrir menu"><Menu size={23}/></button><div><p className="eyebrow">MINHA FAMÍLIA</p><h1>Visão geral</h1></div><div className="user-badge">360</div></header>{children}</main></div>}
function Dashboard({family,items}:{family:Family;items:MapItem[]}){const done=items.filter(i=>i.completed).length;const progress=items.length?Math.round(done/items.length*100):0;return <div className="content"><section className="welcome"><div><span className="pill">● EM ORGANIZAÇÃO</span><h2>{family.name}, um mapa por vez.</h2><p>Organize as informações importantes e deixe claro onde está cada coisa e quem pode ajudar.</p></div><div className="progress-ring"><strong>{progress}%</strong><span>concluído</span></div></section><section className="section-head"><div><h3>Os 7 mapas da família</h3><p>Comece pelo que hoje está mais espalhado.</p></div></section><div className="map-grid">{maps.map((m,i)=>{const count=items.filter(x=>x.map_key===m.id).length;return <NavLink className="map-card" key={m.id} to={'/mapa/'+m.id}><div className="map-icon"><m.icon size={23}/></div><div><span className="map-number">MAPA {i+1}</span><h4>{m.label}</h4><p>{m.desc}</p><small>{count} {count===1?'item':'itens'}</small></div><ArrowRight size={19} className="arrow"/></NavLink>})}</div><section className="security-note"><Shield size={22}/><div><strong>Privacidade primeiro</strong><p>O Dossiê organiza referências. Nunca informe aqui senhas, PINs, tokens ou códigos de autenticação.</p></div></section></div>}
function MapPage({familyId,id,items,onSaved}:{familyId:string;id:string;items:MapItem[];onSaved:(item:MapItem)=>void}){const map=maps.find(m=>m.id===id)??maps[0];const[title,setTitle]=useState('');const[location,setLocation]=useState('');const[responsible,setResponsible]=useState('');const[saved,setSaved]=useState(false);const mapItems=items.filter(x=>x.map_key===map.id);async function submit(){if(!title.trim())return;try{const item=await saveMapItem(familyId,map.id,{title:title.trim(),location_reference:location.trim()||null,notes:responsible.trim()||null,completed:false});onSaved(item);setTitle('');setLocation('');setResponsible('');setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e){console.error(e)}}return <div className="content"><div className="breadcrumb">Visão geral / {map.label}</div><section className="page-intro"><div className="map-icon large"><map.icon size={30}/></div><div><span className="map-number">MAPA {maps.findIndex(x=>x.id===map.id)+1} DE 7</span><h2>{map.label}</h2><p>{map.desc}</p></div></section><div className="form-card"><div className="form-title"><div><h3>Adicionar informação</h3><p>Preencha apenas o que for útil para sua família.</p></div><CheckCircle2 size={24}/></div><label>Nome / identificação<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Conta principal, médico de referência..."/></label><label>Onde encontrar / referência<textarea value={location} onChange={e=>setLocation(e.target.value)} placeholder="Ex.: pasta física, aplicativo, instituição, endereço..."/></label><label>Responsável<input value={responsible} onChange={e=>setResponsible(e.target.value)} placeholder="Quem sabe resolver ou pode orientar?"/></label><div className="form-actions"><button className="btn primary" onClick={submit}>{saved?'Salvo ✓':'Salvar informação'}</button></div></div>{mapItems.length>0&&<section className="items-list"><h3>Informações cadastradas</h3>{mapItems.map(item=><div className="saved-item" key={item.id}><strong>{item.title}</strong><span>{item.location_reference||'Sem referência cadastrada'}</span>{item.notes&&<small>Responsável: {item.notes}</small>}</div>)}</section>}<section className="tip"><FileText size={20}/><div><strong>Uma regra simples</strong><p>Se outra pessoa precisasse resolver isso amanhã, ela saberia por onde começar?</p></div></section></div>}
function App(){const[session,setSession]=useState<any>(undefined);const[family,setFamily]=useState<Family|null>(null);const[items,setItems]=useState<MapItem[]>([]);useEffect(()=>{if(!supabase){setSession(null);return}supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:listener}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>listener.subscription.unsubscribe()},[]);useEffect(()=>{if(!session?.user?.id)return;(async()=>{try{const f=await getOrCreateFamily(session.user.id);setFamily(f);setItems(await listMapItems(f.id))}catch(e){console.error(e)}})()},[session]);if(session===undefined)return <div className="loading-screen">Carregando seu dossiê…</div>;if(!session)return <Auth onAuthed={()=>{}}/>;if(!family)return <div className="loading-screen">Preparando seu espaço familiar…</div>;return <Layout onLogout={()=>supabase?.auth.signOut()}><Routes><Route path="/" element={<Dashboard family={family} items={items}/>}/><Route path="/mapa/:id" element={<MapRoute familyId={family.id} items={items} onSaved={item=>setItems(prev=>[...prev,item])}/>}/><Route path="*" element={<Dashboard family={family} items={items}/>} /></Routes></Layout>}
function MapRoute({familyId,items,onSaved}:{familyId:string;items:MapItem[];onSaved:(item:MapItem)=>void}){const{id='pessoas'}=useParams();return <MapPage familyId={familyId} id={id} items={items} onSaved={onSaved}/>}
export default App;
